
GET http://localhost:3001/users


###Insertar usuario

POST http://localhost:3001/users
Content-Type: application/json

{
"username": "ruben",
"email": "ruben@example.com",
"password": "yes",
"name": "ruben",
"firstName": "PrimerNombre2",
"position": "Posición2",
"league": "Liga2",
"isChat": false
    
}
### get by id
GET http://localhost:3001/1b48d05a-05e2-4f5c-b72b-e0d1be1cebf9

### DELETE BY ID

DELETE  http://localhost:3001/users/48a02926-e350-4138-874e-94078c6df3cb

### update user
PATCH http://localhost:3001/users/f8846612-4407-44e3-8329-bf46457ac54a
Content-Type: application/json

{
    "email":"sdf@gmail.com",
    "username":"rubenelmejor",
    "name":"bichosexual"
}

#####
##          USERS
#####



### create user // registre

POST http://localhost:3001/users/register
Content-Type: application/json

{
"username": "casanco2000",
"email": "casanco2000@example.com",
"password": "casanco",
"name": "carlos",
"firstName": "Santiago",
"isChat":true
}

### login user

POST http://localhost:3001/users/mongo/login
Content-Type: application/json

{
"username": "funcionaelupdate",
"password": "plex"
}


### recoger todos users
 
GET http://localhost:3001/users/mongo/get

### user by id

GET http://localhost:3001/users/mongo/663bbb5c235b5bd1c3f8f393

### users by ischat= true
GET http://localhost:3001/users/mongo/chat

### delete by id
DELETE http://localhost:3001/users/mongo/663a98fb0c738078b25f4cfb

###

PATCH http://localhost:3001/users/mongo/663bbb5c235b5bd1c3f8f393
Content-Type: application/json

{   
    "name":"HALA MADRID",
    "password": "plex"
}


#####
##          BOOKING
#####


POST http://localhost:3001/booking
Content-Type: application/json

{
    "pista":1,
    "hora":2230,
    "diaReserva":"2024-03-12",
    "idUsuario":"6639f7aef296fef7476837f3"
}

### DELETE BOOKING BY ID

DELETE http://localhost:3001/booking/

#### get booking by idUser
GET http://localhost:3001/booking/6639f7aef296fef7476837f3

###
